version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install

  build:
    commands:
      - echo Build started on $(date)
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'                 # Include all files from the build
  name: webapp-artifact.zip  # Optional: Name of the artifact file
